#!/usr/bin/env python3
"""Regenerate the Council Library Plans Progression.md dashboard.

Implements the detection engine described in the update-plans-progression /
plans-progression-dashboard / council-library-plan-completion skills (which live
in Shared_Skills and ship no runnable script — this is the working copy).

Run after ANY change to a planning document (tick, new plan, move).

Usage:
    python3 scripts/regenerate_progression.py
"""
import io
import os
import re
import datetime

ROOT = '/foreverbox_data/council-library/docs'
DASHBOARD = ROOT + '/Current Reference Documentation/Plans Progression.md'
FOLDERS = ['Current Started Plans', 'Current Completed Plans', 'Current Unstarted Plans', 'archives']

# Template example lines inside the plan's "Task Tracking Template" section are
# NOT real tasks and must never count toward completion percentage.
TEMPLATE_LINES = [
    '- [ ] Criterion 1',
    '- [ ] Criterion 2',
    '- [ ] Test command / manual steps',
    '- [ ] Expected output',
]


def count_tasks(path):
    done = total = 0
    with io.open(path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if line.startswith('- [x] '):
                done += 1
                total += 1
            elif line.startswith('- [ ] ') and line not in TEMPLATE_LINES:
                total += 1
            if re.match(r'^#{1,6}\s+.*\s+-\s+(DONE|COMPLETE|VERIFIED)\s*$', line):
                done += 1
                total += 1
            if re.match(r'^#{1,6}\s+.*\s+-\s+(NOT DONE|BLOCKED|PARTIALLY COMPLETE)\s*$', line):
                total += 1
    return done, total


def main():
    rows = []
    started_total = started_done = 0
    moved = []

    for folder in FOLDERS:
        p = os.path.join(ROOT, folder)
        if not os.path.isdir(p):
            continue
        for fname in sorted(os.listdir(p)):
            if not fname.endswith('.md'):
                continue
            fpath = os.path.join(p, fname)
            done, total = count_tasks(fpath)
            pct = round((done / total) * 100) if total else 100
            rows.append((fname, folder, done, total, pct))
            if folder == 'Current Started Plans':
                started_done += done
                started_total += total
                # Auto-relocate 100% plans from Started to Completed
                if total > 0 and done == total:
                    os.rename(fpath, os.path.join(ROOT, 'Current Completed Plans', fname))
                    moved.append(f"MOVED: {fname} -> Current Completed Plans")
                    rows[-1] = (fname, 'Current Completed Plans', done, total, pct)

    overall = round((started_done / started_total) * 100) if started_total else 100
    lines = [
        '# Plans Progression\n',
        f'*Regenerated {datetime.date.today().isoformat()}*\n',
        f'**Overall completion (Started + Unstarted): {overall}%**\n',
        '| Plan | Folder | Done | Total | % |',
        '|------|--------|------|-------|---|',
    ]
    for fname, folder, done, total, pct in sorted(rows, key=lambda r: r[4], reverse=True):
        lines.append(f'| {fname} | {folder} | {done} | {total} | {pct}% |')
    if moved:
        lines.append('\n## Relocations\n')
        lines.extend(moved)
    lines.append('\n---\n*Auto-generated by update-plans-progression. Do not edit by hand.*\n')

    with io.open(DASHBOARD, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f"Dashboard written: {len(rows)} plans, overall {overall}%")
    for m in moved:
        print(m)


if __name__ == '__main__':
    main()
